{
 "title": "Coms Processes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "# Process Run",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) FROM process_instance"
    }
   ]
  },
  {
   "title": "# Activities",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) FROM process_activity"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT id, code, status, created, updated FROM process_instance order by created desc"
    }
   ]
  },
  {
   "title": "Avg. Execution Time By Activity",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT  description as activity, avg(finish - start) as avg_span FROM process_activity where finish is not null group by description"
    }
   ]
  },
  {
   "title": "Process Activities",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT id, instance_id, description, start, finish FROM process_activity order by id desc"
    }
   ]
  }
 ]
}